version: '3.1'
services:
    odoo:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: odoo16
        ports:
          - "8079:8069"
        depends_on:
            - db
        tty: true
        volumes:
            - filestore:/opt/odoo/data:z
            - ./addons:/mnt/addons
            - ./odoo.conf:/odoo.conf
        restart: unless-stopped
        command: odoo -i base --load base,web --config=odoo.conf

    db:
        image: postgres:15-alpine
        container_name: odoo16_db
        environment:
            POSTGRES_USER: "odoo"
            POSTGRES_PASSWORD: "odoo"
        volumes:
            - db:/var/lib/postgresql/data:z
        restart: unless-stopped

networks:
    default:
        driver_opts:
            encrypted: 1

volumes:
    filestore:
    db:
