version: '3.1'
services:
    odoo:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: odoo17
        ports:
            - "6969:8069"
        depends_on:
            - db
        tty: true
        volumes:
            - filestore:/opt/odoo/data:z
            - ./addons:/mnt/addons
            - ./odoo.conf:/etc/odoo.conf
            - ./requirements.txt:/mnt/requirements.txt
        restart: unless-stopped
        command: sh -c "pip3 install -r /mnt/requirements.txt && odoo -i base --config=/etc/odoo.conf"

    db:
        image: postgres:15-alpine
        container_name: odoo17_db
        environment:
            POSTGRES_USER: "odoo"
            POSTGRES_PASSWORD: "odoo"
        volumes:
            - db:/var/lib/postgresql/data:z
        restart: unless-stopped

networks:
    default:
        driver_opts:
            encrypted: 1

volumes:
    filestore:
    db:
