version: '3.1'
services:
    odoo:
        image: onesinus/odoo-16
        container_name: odoo16
        ports:
          - "8079:8069"
        depends_on:
            - db
        tty: true
        volumes:
            - filestore:/opt/odoo/data:z
            - ./addons:/mnt/addons
            - ./odoo.conf:/etc/odoo.conf
            - ./requirements.txt:/mnt/requirements.txt
        restart: always
        command: sh -c "pip3 install -r /mnt/requirements.txt && odoo --config=/etc/odoo.conf -i base"

    db:
        image: postgres:15-alpine
        container_name: odoo16_db
        environment:
            POSTGRES_USER: "odoo"
            POSTGRES_PASSWORD: "odoo"
        volumes:
            - db:/var/lib/postgresql/data:z
        restart: unless-stopped

volumes:
    filestore:
    db:
